<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="9" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="84" started-at="2017-10-14T19:42:11Z" finished-at="2017-10-14T19:42:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="84" started-at="2017-10-14T19:42:11Z" finished-at="2017-10-14T19:42:11Z">
      <class name="test.by.epam.homework.creator.TriangleCreatorTest">
        <test-method status="PASS" signature="createTriangleTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleTest" duration-ms="9" started-at="2017-10-14T22:42:11Z" data-provider="validVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Point [x=1.0, y=1.0]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Point [x=3.0, y=1.0]]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Point [x=3.0, y=3.0]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleTest -->
        <test-method status="PASS" signature="createTriangleTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleTest" duration-ms="1" started-at="2017-10-14T22:42:11Z" data-provider="validVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Point [x=0.0, y=0.0]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Point [x=2.0, y=0.0]]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Point [x=0.0, y=-2.0]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleTest -->
        <test-method status="PASS" signature="createTriangleTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleTest" duration-ms="5" started-at="2017-10-14T22:42:11Z" data-provider="validVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Point [x=0.0, y=0.0]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Point [x=2.0, y=2.0]]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Point [x=-2.0, y=2.0]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleTest -->
        <test-method status="PASS" signature="createTriangleWithInvalidDataExceptionTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleWithInvalidDataExceptionTest" duration-ms="11" started-at="2017-10-14T22:42:11Z" data-provider="invalidVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Point [x=1.0, y=3.0]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Point [x=-4.0, y=3.0]]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Point [x=3.0, y=3.0]]]>
              </value>
            </param>
          </params>
          <exception class="by.epam.homework.exception.TriangleCreatorException">
            <message>
              <![CDATA[Triangle can not be created, wrong coordinates.]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.homework.exception.TriangleCreatorException: Triangle can not be created, wrong coordinates.
	at by.epam.homework.creator.TriangleCreator.createTriangle(TriangleCreator.java:53)
	at test.by.epam.homework.creator.TriangleCreatorTest.createTriangleWithInvalidDataExceptionTest(TriangleCreatorTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.homework.exception.TriangleCreatorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleWithInvalidDataExceptionTest -->
        <test-method status="PASS" signature="createTriangleWithInvalidDataExceptionTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleWithInvalidDataExceptionTest" duration-ms="10" started-at="2017-10-14T22:42:11Z" data-provider="invalidVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Point [x=-2.0, y=0.0]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Point [x=-2.0, y=4.0]]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Point [x=-2.0, y=-2.0]]]>
              </value>
            </param>
          </params>
          <exception class="by.epam.homework.exception.TriangleCreatorException">
            <message>
              <![CDATA[Triangle can not be created, wrong coordinates.]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.homework.exception.TriangleCreatorException: Triangle can not be created, wrong coordinates.
	at by.epam.homework.creator.TriangleCreator.createTriangle(TriangleCreator.java:53)
	at test.by.epam.homework.creator.TriangleCreatorTest.createTriangleWithInvalidDataExceptionTest(TriangleCreatorTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.homework.exception.TriangleCreatorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleWithInvalidDataExceptionTest -->
        <test-method status="PASS" signature="createTriangleWithInvalidDataExceptionTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleWithInvalidDataExceptionTest" duration-ms="2" started-at="2017-10-14T22:42:11Z" data-provider="invalidVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Point [x=4.0, y=4.0]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Point [x=0.0, y=0.0]]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Point [x=3.0, y=3.0]]]>
              </value>
            </param>
          </params>
          <exception class="by.epam.homework.exception.TriangleCreatorException">
            <message>
              <![CDATA[Triangle can not be created, wrong coordinates.]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.homework.exception.TriangleCreatorException: Triangle can not be created, wrong coordinates.
	at by.epam.homework.creator.TriangleCreator.createTriangle(TriangleCreator.java:53)
	at test.by.epam.homework.creator.TriangleCreatorTest.createTriangleWithInvalidDataExceptionTest(TriangleCreatorTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.homework.exception.TriangleCreatorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleWithInvalidDataExceptionTest -->
        <test-method status="PASS" signature="createTriangleWithNullDataExceptionTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleWithNullDataExceptionTest" duration-ms="1" started-at="2017-10-14T22:42:11Z" data-provider="nullVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value>
                <![CDATA[Point [x=-4.0, y=3.0]]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Point [x=3.0, y=3.0]]]>
              </value>
            </param>
          </params>
          <exception class="by.epam.homework.exception.TriangleException">
            <message>
              <![CDATA[Null triangle reference]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.homework.exception.TriangleException: Null triangle reference
	at by.epam.homework.validator.TriangleValidator.isTriangleExist(TriangleValidator.java:14)
	at by.epam.homework.creator.TriangleCreator.createTriangle(TriangleCreator.java:49)
	at test.by.epam.homework.creator.TriangleCreatorTest.createTriangleWithNullDataExceptionTest(TriangleCreatorTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.homework.exception.TriangleException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleWithNullDataExceptionTest -->
        <test-method status="PASS" signature="createTriangleWithNullDataExceptionTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleWithNullDataExceptionTest" duration-ms="1" started-at="2017-10-14T22:42:11Z" data-provider="nullVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Point [x=-2.0, y=0.0]]]>
              </value>
            </param>
            <param index="1">
              <value is-null="true"/>
            </param>
            <param index="2">
              <value>
                <![CDATA[Point [x=-2.0, y=-2.0]]]>
              </value>
            </param>
          </params>
          <exception class="by.epam.homework.exception.TriangleException">
            <message>
              <![CDATA[Null triangle reference]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.homework.exception.TriangleException: Null triangle reference
	at by.epam.homework.validator.TriangleValidator.isTriangleExist(TriangleValidator.java:14)
	at by.epam.homework.creator.TriangleCreator.createTriangle(TriangleCreator.java:49)
	at test.by.epam.homework.creator.TriangleCreatorTest.createTriangleWithNullDataExceptionTest(TriangleCreatorTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.homework.exception.TriangleException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleWithNullDataExceptionTest -->
        <test-method status="PASS" signature="createTriangleWithNullDataExceptionTest(by.epam.homework.entity.Point, by.epam.homework.entity.Point, by.epam.homework.entity.Point)[pri:0, instance:test.by.epam.homework.creator.TriangleCreatorTest@3d74bf60]" name="createTriangleWithNullDataExceptionTest" duration-ms="2" started-at="2017-10-14T22:42:11Z" data-provider="nullVertexData" finished-at="2017-10-14T22:42:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Point [x=4.0, y=4.0]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Point [x=0.0, y=0.0]]]>
              </value>
            </param>
            <param index="2">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="by.epam.homework.exception.TriangleException">
            <message>
              <![CDATA[Null triangle reference]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.epam.homework.exception.TriangleException: Null triangle reference
	at by.epam.homework.validator.TriangleValidator.isTriangleExist(TriangleValidator.java:14)
	at by.epam.homework.creator.TriangleCreator.createTriangle(TriangleCreator.java:49)
	at test.by.epam.homework.creator.TriangleCreatorTest.createTriangleWithNullDataExceptionTest(TriangleCreatorTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.epam.homework.exception.TriangleException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTriangleWithNullDataExceptionTest -->
      </class> <!-- test.by.epam.homework.creator.TriangleCreatorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
